import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Artifact — Bash",
  description: "An internal creative sharing platform for Bash.",
  icons: {
    // PNG generated by app/icon.tsx — works in all browsers including Safari
    icon: [{ url: "/icon", type: "image/png", sizes: "48x48" }],
    // iOS home screen icon — 180×180 PNG
    apple: [{ url: "/apple-icon", type: "image/png", sizes: "180x180" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col bg-[var(--background)] text-[var(--foreground)]">
        <Navbar />
        <main className="flex-1 flex flex-col min-h-0 pb-32 md:pb-0">{children}</main>
      </body>
    </html>
  );
}
